server:
  port: 8082

spring:
  application:
    name: order-service
  grpc:
    server:
      port: 9092
    client:
      product-service:
        address: discovery:///product-service
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      grpc.port: ${spring.grpc.server.port:9092}

