server:
  port: 8081

spring:
  application:
    name: product-service
  grpc:
    server:
      port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      grpc.port: ${spring.grpc.server.port:9091}

